#!/bin/bash
sed -i "/^Version/c\Version: $TRAVIS_TAG" style.css && sed -i "/^Template/c\Template: boldgrid-crio" style.css && zip -r crio-child.zip . -x .\* -x codesniffer.ruleset.xml -x gulpfile.js -x package.json -x bower.json -x release
